language: python
before_install:
  - sudo apt-get install -qq libatlas3gf-base libatlas-dev liblapack-dev gfortran
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then conda create --yes -q -n pyenv python=2.6 cython=0.2 pillow numpy=1.6 numpydoc scipy=0.11 pytables=3.0 numexpr=2.2.2 nose=1.1 pyyaml sphinx pyflakes argparse pip matplotlib scikit-learn h5py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then conda create --yes -q -n pyenv python=3.4 cython=0.21.1 pillow numpy=1.9.1 numpydoc scipy=0.14.0 pytables=3.1.1 numexpr=2.3.1 nose=1.3.4 pyyaml sphinx pyflakes pip matplotlib scikit-learn h5py; fi
  - source activate pyenv
  - pip install -q git+git://git.assembla.com/jobman.git
  - pip install -q --no-deps git+git://github.com/Theano/Theano.git
  - pip install -q nose-exclude
  - python setup.py develop
  - pip install -q pyzmq --install-option="--zmq=bundled"
matrix:
  include:
    - python: "2.6"
      env: FLAGS=floatX=float64 PART="--exclude-dir=pylearn2/models"
    - python: "2.6"
      env: FLAGS=floatX=float64 PART=pylearn2/models
    - python: "2.6"
      env: TEST_DOC=YES
    - python: "3.4"
      env: FLAGS=floatX=float32 PART="--exclude-dir=pylearn2/models"
    - python: "3.4"
      env: FLAGS=floatX=float32 PART=pylearn2/models
script:
  - sh .travis.sh
