# After changing this file, check it on:
# http://lint.travis-ci.org/

## Use language: c to avoid being trapped in a virtualenv,
# so we can use "apt-get" (instead of "pip" )to install scipy,
# as pip takes much too long.
language: c

#language: python
#python:
#Currently we use functools.cmp_to_key that is available only in python 2.7
#  - "2.7"


# command to install dependencies
before_install:
  - sudo apt-get install -qq libatlas3gf-base libatlas-dev
    python-numpy python-scipy python-pip python-nose python-yaml
    pyflakes python-imaging

# The "|| cat ..." part prints the error log if the pip command fails
install:
  - "sudo pip install -q git+git://git.assembla.com/jobman.git || cat /home/travis/.pip/pip.log"
  - "sudo pip install -q --no-deps git+git://github.com/Theano/Theano.git || cat /home/travis/.pip/pip.log"

# command to run tests
#env:
#  - PART="theano/tensor/nnet/ theano/tensor/signal/ theano/compile/ theano/gof/ theano/misc/ theano/scalar/ theano/tests/"
#  - PART="theano/scan_module/ theano/sandbox theano/sparse"

# Start testing
script:
#We can't build the test dataset as the original is not present. We can't download the original as it
# is too big to download each time. If present run: python make_dataset.py
  - cd pylearn2/scripts/train_example/
  - wget http://www.iro.umontreal.ca/~lisa/datasets/cifar10_preprocessed_train.pkl
  - cd ../../..
  - export THEANO_FLAGS=warn.ignore_bug_before=all,on_opt_error=raise,on_shape_error=raise
  - export TRAVIS=1
  - theano-nose
